# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Update Homebrew
update

# Upgrade current packages 
upgrade

# Basic Taps
tap homebrew/dupes
tap homebrew/versions

# Cask + alt versions 
tap caskroom/cask
tap caskroom/versions
install brew-cask

# Install GNU utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
install findutils

# Install more recent versions of some OS X tools
# Don't forget to add /usr/local/bin/bash to /etc/shells
install bash
install vim --override-system-vi
install homebrew/dupes/grep

# PHP
tap homebrew/homebrew-php
install homebrew/php/php55 --with-gmp

install git
install hub
install imagemagick --with-webp
install lynx
install node
install ssh-copy-id
install wget 

# Pythons
install python
install python3


# Remove outdated versions from the cellar
cleanup
